#!/usr/bin/env python3
"""Generate the component catalogue from the ecosystem manifest.

The manifest is the single source of truth for component composition. This
script projects it into a reference page so the catalogue cannot drift.

Usage:
    python3 tools/generate_components.py <path-to-components.toml>
"""
import datetime
import sys
import tomllib
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "reference" / "components.md"
LAYER_ORDER = {"brain": 0, "mind": 1, "soma": 2}


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: generate_components.py <components.toml>")
    manifest_path = Path(sys.argv[1])
    data = tomllib.loads(manifest_path.read_text(encoding="utf-8"))
    components = data.get("component", {})
    if not components:
        sys.exit(f"no [component.*] tables found in {manifest_path}")

    today = datetime.date.today().isoformat()
    rows = sorted(
        components.items(),
        key=lambda kv: (LAYER_ORDER.get(kv[1].get("layer", ""), 9), kv[0]),
    )

    lines = [
        "---",
        "title: Component catalogue",
        "type: reference",
        'summary: "Every component in the manifest, with its layer, channel, licence, and owning repository."',
        "audience: operator",
        "status: current",
        f"verified: {today}",
        "---",
        "",
        "<!-- Generated by tools/generate_components.py from manifests/components.toml.",
        "     Do not edit by hand; edit the manifest and regenerate. -->",
        "",
        "# Component catalogue",
        "",
        "Every component declared in the ecosystem manifest. The manifest is the",
        "single source of truth; this page is generated from it.",
        "",
        "A component is a declared capability. Several components are provided by the",
        "same repository: [ADR-0019](../governance/adr/0019-shesh-core-monorepo.md)",
        "consolidated sixteen single-module repositories into `shesh-core` while keeping",
        "the component declarations and command names unchanged.",
        "",
    ]

    for layer in ("brain", "mind", "soma"):
        group = [(n, c) for n, c in rows if c.get("layer") == layer]
        if not group:
            continue
        lines += [
            f"## {layer.capitalize()} layer",
            "",
            "| Component | Channel | Licence | Repository | Provides |",
            "|---|---|---|---|---|",
        ]
        for name, c in group:
            repo = c.get("repo", "")
            repo_cell = f"[{repo}](https://github.com/{repo})" if repo else "—"
            provides = ", ".join(f"`{p}`" for p in c.get("provides", [])) or "—"
            lines.append(
                f"| `{name}` | {c.get('channel', '—')} | {c.get('license', '—')} "
                f"| {repo_cell} | {provides} |"
            )
        lines.append("")

    other = [(n, c) for n, c in rows if c.get("layer") not in LAYER_ORDER]
    if other:
        lines += ["## Unclassified", "", "| Component | Repository |", "|---|---|"]
        for name, c in other:
            lines.append(f"| `{name}` | {c.get('repo', '—')} |")
        lines.append("")

    lines += [
        "## Related",
        "",
        "- [Manifest schema](manifest-schema.md) — the meaning of each field above.",
        "- [Release channels](release-channels.md) — what the channel column implies.",
        "- [Repository topology](../explanation/repository-topology.md) — why components",
        "  and repositories are not one to one.",
        "",
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} components)")


if __name__ == "__main__":
    main()
